services:
  vote:
    build: 
      context: ./vote
      dockerfile: Dockerfile
      target: dev
    depends_on:
      redis:
       condition: service_healthy 
    ports:
      - "80:80" 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    volumes:
      - ./vote:/usr/local/app  
  result:
    build: 
      context: ./result
      dockerfile: Dockerfile
    depends_on:
        db:
          condition: service_healthy
    volumes:
      - ./result:/usr/local/app      
    ports:
      - "8091:80"

  worker:
    build: 
      context: ./worker
      dockerfile: Dockerfile
    depends_on:
        db:
          condition: service_healthy
        redis:
          condition: service_healthy

  redis:
      image: redis:6-alpine
      volumes:
        - redis-data:/data
      healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 30s
        timeout: 10s
        retries: 5
        start_period: 10s

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  db-data:
  redis-data:
