name: deploy to ec2
on:
  push:
    branches:
      - main
    paths:
        - results/**
        - vote/**
        - worker/**
        - .github/workflows/build.YAML
        - docker-compose.yaml
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2 
       
        - name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and push Docker image
          uses: docker/build-push-action@v2
          with:
            context: .
            file: docker-compose.yaml
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest

        - name: Deploy to EC2
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USERNAME }}
            key: ${{ secrets.EC2_PRIVATE_KEY }}
            script: |
              docker pull ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest
              docker run -d -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest

    deploy-to-ec2:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2 
       
        - name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and push result service
          uses: docker/build-push-action@v4
          with:
            context: ./result
            file: ./result/Dockerfile
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/result:latest

        - name: Build and push vote service
          uses: docker/build-push-action@v4
          with:
            context: ./vote
            file: ./vote/Dockerfile
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/vote:latest

        - name: Build and push worker service
          uses: docker/build-push-action@v4
          with:
            context: ./worker
            file: ./worker/Dockerfile
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/worker:latest      

        - name: Deploy to EC2
          runs-on: ubuntu-latest
          needs: build-and-push

          steps:
          - name: set up SSH
            uses: webfactory/ssh-agent@v0.5.4
            with:
              ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

              -name: copy docker-compose file
              run: scp -o StrictHostKeyChecking=no docker-compose.yaml ${{ secrets.secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu-latest