name: deploy-to-ec2

on:
  push:
    branches: [ main ]
    paths:
      - "vote/**"
      - "result/**"
      - "worker/**"
      - "docker-compose.yaml"
      - ".github/workflows/deploy.yml"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push result
        uses: docker/build-push-action@v6
        with:
          context: ./result
          file: ./result/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/result:latest
          platforms: linux/amd64
          provenance: false
          no-cache: true

      - name: Build & push worker
        uses: docker/build-push-action@v6
        with:
          context: ./worker
          file: ./worker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/worker:latest
          platforms: linux/amd64
          provenance: false
          no-cache: true

      - name: Build & push vote
        uses: docker/build-push-action@v6
        with:
          context: ./vote
          file: ./vote/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/vote:latest
          platforms: linux/amd64
          provenance: false
          no-cache: true

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1) Load your EC2 private key into the SSH agent
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # 2) Ensure target dir and copy compose file to /opt/app
      - name: Prepare remote & copy compose
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'sudo mkdir -p /opt/app && sudo chown $USER:$USER /opt/app'
          scp -o StrictHostKeyChecking=no docker-compose.yaml ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/opt/app/docker-compose.yaml

      # 3) SSH and deploy with Docker Compose
      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} <<'EOSSH'
            set -e
            cd /opt/app

            # Ensure Docker Engine
            if ! command -v docker >/dev/null 2>&1; then
              sudo apt-get update -y
              sudo apt-get install -y docker.io curl
              sudo systemctl enable --now docker
            fi

            # Ensure Docker Compose v2 (standalone binary)
            if ! docker compose version >/dev/null 2>&1; then
              ARCH=$(uname -m)
              BIN="docker-compose-linux-x86_64"
              if [ "$ARCH" = "aarch64" ] || [ "$ARCH" = "arm64" ]; then BIN="docker-compose-linux-aarch64"; fi
              sudo mkdir -p /usr/local/lib/docker/cli-plugins
              sudo curl -SL "https://github.com/docker/compose/releases/download/v2.29.7/$BIN" \
                -o /usr/local/lib/docker/cli-plugins/docker-compose
              sudo chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
            fi

            # Login & run
            sudo docker login -u '${{ secrets.DOCKERHUB_USERNAME }}' -p '${{ secrets.DOCKERHUB_TOKEN }}'
            sudo docker compose -f docker-compose.yaml pull
            sudo docker compose -f docker-compose.yaml up -d
            sudo docker compose -f docker-compose.yaml ps
          EOSSH

